---
- name: install webserver
  hosts: terra_ansible_host
  gather_facts: no
  become: true

  tasks:

    - name: Install a list of packages
      yum:
        name:
          - nginx
        state: present

    - name: start ngnix
      service:
          name: nginx
          state: started
...

